name: Load Assessment Data to BigQuery

on:
  push:
    branches:
      - main
    paths:
      - 'data/assessments/**'

jobs:
  load-data:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g., projects/12345/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g., my-service-account@my-project.iam.gserviceaccount.com

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your preferred Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r app/requirements.txt

    - name: Load data to BigQuery
      run: |
        source venv/bin/activate
        make bq-load
