name: Test GCP WIF

on:
  workflow_dispatch: # run manually

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # REQUIRED to get an OIDC token from GitHub
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP with WIF
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/281304798313/locations/global/workloadIdentityPools/github-pool/providers/github"
        service_account: "github-actions-sa@development-9e37b3cd.iam.gserviceaccount.com"

    - name: Run gcloud to test auth
      run: |
        gcloud auth list
        gcloud projects get-iam-policy development-9e37b3cd --format=json
